### PR TITLE
Fix module detection (for real this time)

### PR DESCRIPTION
**Pull request by pfitzseb**
by using Tokenize.jl.

Should actually work this time around...

@marius311 Since you reported the bugs related to this, would you mind trying out this branch?

### CODE REVIEW

**Comment by marius311** [comment]
Awesome, thanks for this. I'll play around with it this weekend and report back.

**Comment by MikeInnes** [comment]
Is this good to go as far as you're concerned? Would be great to get this in the next release.

**Comment by sglyon** [comment]
Can we add some test to see if annotating loops works?

I frequently have issues with code like this (forget the pointless code that doesn't do anything):

```julia
module Mod

    function foo(n)
        x = zeros(n)
        @inbounds for i 1:n
            x = sin(x)
        end
    end

end  # module
```

When I don't have `@inbounds`, it works fine. When I do have it Juno thinks the module ends when the `@inbounds for` does

**Comment by pfitzseb** [comment]
I'm 99% sure this works now, but adding that test would be awesome regardless (maybe you could do that, @sglyon?).

**Comment by marius311** [comment]
Sorry I never got back on this, having just checked I confirm it looks like it resolves everything I mentioned in https://github.com/JunoLab/atom-julia-client/issues/308, as well as @sglyon's code from above. I also haven't found any other new problems. 

https://github.com/JunoLab/atom-julia-client/issues/198 however is still unresolved however, although that's more block detection as opposed to module detection I suppose.

**Comment by MikeInnes** [comment]
Yup, block detection happens on the Atom/JS side. Will take a quick look at that.

**Pull request merged**
